### ISSUE TITLE
buy domain

### ISSUE THREAD

**Issue by lucaspelloni2** [lucaspelloni2/crypto-portfolio#1]
www.cryptotwint.com is available and costs 14.90 USD.

What do you think? 

@severinwullschleger @ZobRob @anschau1992 @RaphaelRo

**Comment by Zobrob** [comment]
That's fine for me; if you want to go with a free one there are some available on Freenom.com (.tk,.ml,..). For "currencyeye" there would be .net or .org available(for 6/8.60EUR).

**Comment by severinwullschleger** [comment]
Also thought about the part “twint”. Is it a good idea to use that already branded term. I’m in for a paying a bit for the domain. I checked out “currencytransfer” but was not so into that. We could go with currencyeye.org . It is cheaper and was our original title, so why not?

**Comment by lucaspelloni2** [comment]
Hi guys, thanks for the answers. I see your points. However, this is a cool project and I would like to have it in my SW-portfolio.
So in my opinion www.cryptotwint.com has much more impact that just ".org" or whatever. 
So I will pay the difference, don't worry about that ;) 
--> PS: -1 cafe --> + 1 cool domain ;)

**Comment by severinwullschleger** [comment]
My main point is the “twint” part and not the costs. The costs don’t matter.  I’m in with that if .com is better than .org, didn’t know that. 

 

I’m ok with cryptotwint.com but also with currencyeye.com or whatever.

**Comment by Zobrob** [comment]
Yes, my suggestion for .org was because of the name not price (.com are even cheaper than .org on freenom ;) ). Currencyeye.com is not available. Just take whatever you think is best and write what it costs for the domain and server. Thank you.
